// frontend-next/app/login/page.tsx
"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { setCookie } from "@/lib/auth"
import { wifIsValid, wifToPublic, findAccountsByKey, getAccount } from "@/lib/viz"
import { useViz } from "@/contexts/VizContext"

export default function LoginPage() {
  const [wif, setWif] = useState("")
  const [accountName, setAccountName] = useState("")
  const [error, setError] = useState("")
  const [loading, setLoading] = useState(false)
  const router = useRouter()
  const { ready, refreshAccount } = useViz()

  async function handleLogin() {
    setError("")
    if (!wif.startsWith("5") || !wifIsValid(wif)) {
      setError("Invalid private key format")
      return
    }

    setLoading(true)
    try {
      const publicKey = wifToPublic(wif)
      let login = accountName.trim().toLowerCase()

      if (!login) {
        const accounts = await findAccountsByKey(publicKey)
        if (!accounts || accounts.length === 0) {
          setError("No account found for this key")
          setLoading(false)
          return
        }
        login = accounts[0]
      }

      const account = await getAccount(login)
      if (!account) {
        setError("Account not found")
        setLoading(false)
        return
      }

      const threshold = account.regular_authority.weight_threshold
      const keyAuths = account.regular_authority.key_auths
      const hasAuth = keyAuths.some(
        ([key, weight]: [string, number]) => key === publicKey && weight >= threshold
      )

      if (!hasAuth) {
        setError("Key does not have sufficient authority")
        setLoading(false)
        return
      }

      setCookie("login", login)
      setCookie("regular", wif)

      try {
        const meta = JSON.parse(account.json_metadata || "{}")
        if (meta.profile?.avatar) {
          setCookie("avatar", meta.profile.avatar)
        }
      } catch {}

      await refreshAccount()
      router.push("/")
    } catch (err: any) {
      setError(err?.message || "Login failed")
    }
    setLoading(false)
  }

  return (
    <div className="max-w-sm mx-auto mt-12">
      <h1 className="text-xl font-bold mb-6">Log In</h1>
      <div className="space-y-4">
        <div>
          <label className="block text-sm text-gray-600 dark:text-gray-400 mb-1">
            Private regular key
          </label>
          <input
            type="password"
            value={wif}
            onChange={(e) => setWif(e.target.value)}
            placeholder="5..."
            className="w-full border border-gray-300 dark:border-gray-600 rounded px-3 py-2 bg-white dark:bg-gray-800"
          />
        </div>
        <div>
          <label className="block text-sm text-gray-600 dark:text-gray-400 mb-1">
            Account name (optional, auto-detected from key)
          </label>
          <input
            type="text"
            value={accountName}
            onChange={(e) => setAccountName(e.target.value)}
            placeholder="account"
            className="w-full border border-gray-300 dark:border-gray-600 rounded px-3 py-2 bg-white dark:bg-gray-800"
          />
        </div>
        {error && <div className="text-red-500 text-sm">{error}</div>}
        <button
          onClick={handleLogin}
          disabled={loading || !ready || !wif}
          className="w-full py-2 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50"
        >
          {loading ? "Logging in..." : "Log In"}
        </button>
      </div>
    </div>
  )
}

// frontend/pages/login.vue
<template>
    <v-container fill-height fluid class="container">
        <v-sheet>
            <v-form fast-fail @submit.prevent="login">

                <div class="wrapper">
                    <v-text-field variant="underlined" v-model="regularKey" label="Private Regular Key" placeholder="5..."
                        :error-messages="errors.key" :rules="[rules.keyValidation]" clearable></v-text-field>
                    <v-btn :icon="!showLogin ? '$expand' : '$collapse'" @click.prevent="showLogin = !showLogin"></v-btn>
                </div>

                <v-text-field v-if="showLogin" variant="underlined" v-model="user" label="Account"
                    :error-messages="errors.user" clearable></v-text-field>

                <v-btn :disabled="!regularKey || rules.keyValidation(regularKey) !== true" type="submit" variant="outlined"
                    color="submit" block class="mt-2">Sign
                    in</v-btn>
            </v-form>
            <div class="mt-2">
                <p class="text-body-2">Don't have an account? <a href="#">Sign Up</a></p>
            </div>
        </v-sheet>
    </v-container>
</template>

<script setup lang="ts">
const { $viz } = useNuxtApp()
const router = useRouter()

let showLogin = ref(false)
let user = ref("")
let regularKey = ref("")

const rules = {
    keyValidation: (value: string) => (!!value && value.startsWith('5')) || 'Private key should starts with 5',
}
let errors: Ref<{
    user: string,
    key: string
}> = ref({ user: "", key: "" })

async function login() {
    let publicRegularKey: string = ""
    if ($viz.auth.isWif(regularKey.value)) {
        publicRegularKey = $viz.auth.wifToPublic(regularKey.value)
    } else {
        errors.value.key = 'Looks like not a private key'
        return
    }
    let login = user.value
    if (!login) {
        let accounts = await findAccountsByKey(publicRegularKey)
        if (accounts.length > 0) {
            login = accounts[0]
        } else {
            errors.value.user = 'Account by key not found'
            return
        }
    }
    getAccount(login).then((account) => {
        errors.value = { user: "", key: "" }
        let regular_authority = account.regular_authority
        let key_weight = 0
        for (let i in regular_authority.key_auths) {
            if (regular_authority.key_auths[i][0] == publicRegularKey) {
                key_weight += regular_authority.key_auths[i][1]
            }
        }
        if (key_weight >= regular_authority.weight_threshold, key_weight >= regular_authority.weight_threshold) {
            // TODO: make cookies more secure
            useCookie('login').value = login
            useCookie('regular').value = regularKey.value

            try {
                let json = JSON.parse(account['json_metadata'])
                let avatar = json['profile']['avatar']
                if (avatar) {
                    useCookie('avatar').value = avatar
                } else {
                    useCookie('avatar').value = undefined
                }
            } catch (e) {
                console.log(e)
            }

            router.push("/")
        } else {
            errors.value.key = 'The weight of the key is not enough'
        }
    }, (err) => {
        errors.value.user = err.message
    })
}
</script>

<style>
.wrapper {
    display: flex;
}

.container {
    max-width: 580px;
}
</style>
